<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>FolderMorpher</AssemblyName>
    <RootNamespace>FolderMorpher</RootNamespace>
    <ApplicationTitle>FolderMorpher - Storage &amp; Migration Studio</ApplicationTitle>
    <Version>1.2.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="System.DirectoryServices" Version="8.0.0" />
  </ItemGroup>

</Project>
