<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>false</UseWPF>
    <AssemblyName>FolderMorpher.Host</AssemblyName>
    <RootNamespace>FolderMorpher.Host</RootNamespace>
    <Version>2.2.33</Version>
    <CodePage>65001</CodePage>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StreamJsonRpc" Version="2.25.29" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FolderMorpher.Core\FolderMorpher.Core.csproj" />
    <ProjectReference Include="..\FolderMorpher.Contracts\FolderMorpher.Contracts.csproj" />
  </ItemGroup>

</Project>
